class PlayerProfile < ::ApplicationRecord
  extend ::_ActiveRecord_Relation_ClassMethods[::PlayerProfile, ::PlayerProfile::ActiveRecord_Relation, ::Integer]

  module GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def player_id: () -> ::Integer

    def player_id=: (::Integer) -> ::Integer

    def player_id?: () -> bool

    def player_id_changed?: () -> bool

    def player_id_change: () -> [ ::Integer?, ::Integer? ]

    def player_id_will_change!: () -> void

    def player_id_was: () -> ::Integer?

    def player_id_previously_changed?: () -> bool

    def player_id_previous_change: () -> ::Array[::Integer?]?

    def player_id_previously_was: () -> ::Integer?

    def player_id_before_last_save: () -> ::Integer?

    def player_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def player_id_in_database: () -> ::Integer?

    def saved_change_to_player_id: () -> ::Array[::Integer?]?

    def saved_change_to_player_id?: () -> bool

    def will_save_change_to_player_id?: () -> bool

    def restore_player_id!: () -> void

    def clear_player_id_change: () -> void

    def entry_list_name: () -> ::String

    def entry_list_name=: (::String) -> ::String

    def entry_list_name?: () -> bool

    def entry_list_name_changed?: () -> bool

    def entry_list_name_change: () -> [ ::String?, ::String? ]

    def entry_list_name_will_change!: () -> void

    def entry_list_name_was: () -> ::String?

    def entry_list_name_previously_changed?: () -> bool

    def entry_list_name_previous_change: () -> ::Array[::String?]?

    def entry_list_name_previously_was: () -> ::String?

    def entry_list_name_before_last_save: () -> ::String?

    def entry_list_name_change_to_be_saved: () -> ::Array[::String?]?

    def entry_list_name_in_database: () -> ::String?

    def saved_change_to_entry_list_name: () -> ::Array[::String?]?

    def saved_change_to_entry_list_name?: () -> bool

    def will_save_change_to_entry_list_name?: () -> bool

    def restore_entry_list_name!: () -> void

    def clear_entry_list_name_change: () -> void

    def family_name: () -> ::String

    def family_name=: (::String) -> ::String

    def family_name?: () -> bool

    def family_name_changed?: () -> bool

    def family_name_change: () -> [ ::String?, ::String? ]

    def family_name_will_change!: () -> void

    def family_name_was: () -> ::String?

    def family_name_previously_changed?: () -> bool

    def family_name_previous_change: () -> ::Array[::String?]?

    def family_name_previously_was: () -> ::String?

    def family_name_before_last_save: () -> ::String?

    def family_name_change_to_be_saved: () -> ::Array[::String?]?

    def family_name_in_database: () -> ::String?

    def saved_change_to_family_name: () -> ::Array[::String?]?

    def saved_change_to_family_name?: () -> bool

    def will_save_change_to_family_name?: () -> bool

    def restore_family_name!: () -> void

    def clear_family_name_change: () -> void

    def family_name_kana: () -> ::String

    def family_name_kana=: (::String) -> ::String

    def family_name_kana?: () -> bool

    def family_name_kana_changed?: () -> bool

    def family_name_kana_change: () -> [ ::String?, ::String? ]

    def family_name_kana_will_change!: () -> void

    def family_name_kana_was: () -> ::String?

    def family_name_kana_previously_changed?: () -> bool

    def family_name_kana_previous_change: () -> ::Array[::String?]?

    def family_name_kana_previously_was: () -> ::String?

    def family_name_kana_before_last_save: () -> ::String?

    def family_name_kana_change_to_be_saved: () -> ::Array[::String?]?

    def family_name_kana_in_database: () -> ::String?

    def saved_change_to_family_name_kana: () -> ::Array[::String?]?

    def saved_change_to_family_name_kana?: () -> bool

    def will_save_change_to_family_name_kana?: () -> bool

    def restore_family_name_kana!: () -> void

    def clear_family_name_kana_change: () -> void

    def given_name: () -> ::String

    def given_name=: (::String) -> ::String

    def given_name?: () -> bool

    def given_name_changed?: () -> bool

    def given_name_change: () -> [ ::String?, ::String? ]

    def given_name_will_change!: () -> void

    def given_name_was: () -> ::String?

    def given_name_previously_changed?: () -> bool

    def given_name_previous_change: () -> ::Array[::String?]?

    def given_name_previously_was: () -> ::String?

    def given_name_before_last_save: () -> ::String?

    def given_name_change_to_be_saved: () -> ::Array[::String?]?

    def given_name_in_database: () -> ::String?

    def saved_change_to_given_name: () -> ::Array[::String?]?

    def saved_change_to_given_name?: () -> bool

    def will_save_change_to_given_name?: () -> bool

    def restore_given_name!: () -> void

    def clear_given_name_change: () -> void

    def given_name_kana: () -> ::String

    def given_name_kana=: (::String) -> ::String

    def given_name_kana?: () -> bool

    def given_name_kana_changed?: () -> bool

    def given_name_kana_change: () -> [ ::String?, ::String? ]

    def given_name_kana_will_change!: () -> void

    def given_name_kana_was: () -> ::String?

    def given_name_kana_previously_changed?: () -> bool

    def given_name_kana_previous_change: () -> ::Array[::String?]?

    def given_name_kana_previously_was: () -> ::String?

    def given_name_kana_before_last_save: () -> ::String?

    def given_name_kana_change_to_be_saved: () -> ::Array[::String?]?

    def given_name_kana_in_database: () -> ::String?

    def saved_change_to_given_name_kana: () -> ::Array[::String?]?

    def saved_change_to_given_name_kana?: () -> bool

    def will_save_change_to_given_name_kana?: () -> bool

    def restore_given_name_kana!: () -> void

    def clear_given_name_kana_change: () -> void

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void
  end
  include GeneratedAttributeMethods

  def player: () -> ::Player
  def player=: (::Player?) -> ::Player?
  def reload_player: () -> ::Player?
  def build_player: (untyped) -> ::Player
  def create_player: (untyped) -> ::Player
  def create_player!: (untyped) -> ::Player
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::PlayerProfile::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::PlayerProfile, ::Integer]
    include ::Enumerable[::PlayerProfile]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::PlayerProfile::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::PlayerProfile, ::Integer]
  end
end
