class QuestionReading < ::ApplicationRecord
  extend ::_ActiveRecord_Relation_ClassMethods[::QuestionReading, ::QuestionReading::ActiveRecord_Relation, ::Integer]

  module GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def question_id: () -> ::Integer

    def question_id=: (::Integer) -> ::Integer

    def question_id?: () -> bool

    def question_id_changed?: () -> bool

    def question_id_change: () -> [ ::Integer?, ::Integer? ]

    def question_id_will_change!: () -> void

    def question_id_was: () -> ::Integer?

    def question_id_previously_changed?: () -> bool

    def question_id_previous_change: () -> ::Array[::Integer?]?

    def question_id_previously_was: () -> ::Integer?

    def question_id_before_last_save: () -> ::Integer?

    def question_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def question_id_in_database: () -> ::Integer?

    def saved_change_to_question_id: () -> ::Array[::Integer?]?

    def saved_change_to_question_id?: () -> bool

    def will_save_change_to_question_id?: () -> bool

    def restore_question_id!: () -> void

    def clear_question_id_change: () -> void

    def duration: () -> ::Float?

    def duration=: (::Float?) -> ::Float?

    def duration?: () -> bool

    def duration_changed?: () -> bool

    def duration_change: () -> [ ::Float?, ::Float? ]

    def duration_will_change!: () -> void

    def duration_was: () -> ::Float?

    def duration_previously_changed?: () -> bool

    def duration_previous_change: () -> ::Array[::Float?]?

    def duration_previously_was: () -> ::Float?

    def duration_before_last_save: () -> ::Float?

    def duration_change_to_be_saved: () -> ::Array[::Float?]?

    def duration_in_database: () -> ::Float?

    def saved_change_to_duration: () -> ::Array[::Float?]?

    def saved_change_to_duration?: () -> bool

    def will_save_change_to_duration?: () -> bool

    def restore_duration!: () -> void

    def clear_duration_change: () -> void

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void
  end
  include GeneratedAttributeMethods

  def question: () -> ::Question
  def question=: (::Question?) -> ::Question?
  def reload_question: () -> ::Question?
  def build_question: (untyped) -> ::Question
  def create_question: (untyped) -> ::Question
  def create_question!: (untyped) -> ::Question
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::QuestionReading::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::QuestionReading, ::Integer]
    include ::Enumerable[::QuestionReading]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::QuestionReading::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::QuestionReading, ::Integer]
  end
end
