class Round3CoursePreference < ::ApplicationRecord
  extend ::_ActiveRecord_Relation_ClassMethods[::Round3CoursePreference, ::Round3CoursePreference::ActiveRecord_Relation, ::Integer]

  module GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def player_id: () -> ::Integer

    def player_id=: (::Integer) -> ::Integer

    def player_id?: () -> bool

    def player_id_changed?: () -> bool

    def player_id_change: () -> [ ::Integer?, ::Integer? ]

    def player_id_will_change!: () -> void

    def player_id_was: () -> ::Integer?

    def player_id_previously_changed?: () -> bool

    def player_id_previous_change: () -> ::Array[::Integer?]?

    def player_id_previously_was: () -> ::Integer?

    def player_id_before_last_save: () -> ::Integer?

    def player_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def player_id_in_database: () -> ::Integer?

    def saved_change_to_player_id: () -> ::Array[::Integer?]?

    def saved_change_to_player_id?: () -> bool

    def will_save_change_to_player_id?: () -> bool

    def restore_player_id!: () -> void

    def clear_player_id_change: () -> void

    def choice1_match_id: () -> ::Integer

    def choice1_match_id=: (::Integer) -> ::Integer

    def choice1_match_id?: () -> bool

    def choice1_match_id_changed?: () -> bool

    def choice1_match_id_change: () -> [ ::Integer?, ::Integer? ]

    def choice1_match_id_will_change!: () -> void

    def choice1_match_id_was: () -> ::Integer?

    def choice1_match_id_previously_changed?: () -> bool

    def choice1_match_id_previous_change: () -> ::Array[::Integer?]?

    def choice1_match_id_previously_was: () -> ::Integer?

    def choice1_match_id_before_last_save: () -> ::Integer?

    def choice1_match_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def choice1_match_id_in_database: () -> ::Integer?

    def saved_change_to_choice1_match_id: () -> ::Array[::Integer?]?

    def saved_change_to_choice1_match_id?: () -> bool

    def will_save_change_to_choice1_match_id?: () -> bool

    def restore_choice1_match_id!: () -> void

    def clear_choice1_match_id_change: () -> void

    def choice2_match_id: () -> ::Integer

    def choice2_match_id=: (::Integer) -> ::Integer

    def choice2_match_id?: () -> bool

    def choice2_match_id_changed?: () -> bool

    def choice2_match_id_change: () -> [ ::Integer?, ::Integer? ]

    def choice2_match_id_will_change!: () -> void

    def choice2_match_id_was: () -> ::Integer?

    def choice2_match_id_previously_changed?: () -> bool

    def choice2_match_id_previous_change: () -> ::Array[::Integer?]?

    def choice2_match_id_previously_was: () -> ::Integer?

    def choice2_match_id_before_last_save: () -> ::Integer?

    def choice2_match_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def choice2_match_id_in_database: () -> ::Integer?

    def saved_change_to_choice2_match_id: () -> ::Array[::Integer?]?

    def saved_change_to_choice2_match_id?: () -> bool

    def will_save_change_to_choice2_match_id?: () -> bool

    def restore_choice2_match_id!: () -> void

    def clear_choice2_match_id_change: () -> void

    def choice3_match_id: () -> ::Integer

    def choice3_match_id=: (::Integer) -> ::Integer

    def choice3_match_id?: () -> bool

    def choice3_match_id_changed?: () -> bool

    def choice3_match_id_change: () -> [ ::Integer?, ::Integer? ]

    def choice3_match_id_will_change!: () -> void

    def choice3_match_id_was: () -> ::Integer?

    def choice3_match_id_previously_changed?: () -> bool

    def choice3_match_id_previous_change: () -> ::Array[::Integer?]?

    def choice3_match_id_previously_was: () -> ::Integer?

    def choice3_match_id_before_last_save: () -> ::Integer?

    def choice3_match_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def choice3_match_id_in_database: () -> ::Integer?

    def saved_change_to_choice3_match_id: () -> ::Array[::Integer?]?

    def saved_change_to_choice3_match_id?: () -> bool

    def will_save_change_to_choice3_match_id?: () -> bool

    def restore_choice3_match_id!: () -> void

    def clear_choice3_match_id_change: () -> void

    def choice4_match_id: () -> ::Integer

    def choice4_match_id=: (::Integer) -> ::Integer

    def choice4_match_id?: () -> bool

    def choice4_match_id_changed?: () -> bool

    def choice4_match_id_change: () -> [ ::Integer?, ::Integer? ]

    def choice4_match_id_will_change!: () -> void

    def choice4_match_id_was: () -> ::Integer?

    def choice4_match_id_previously_changed?: () -> bool

    def choice4_match_id_previous_change: () -> ::Array[::Integer?]?

    def choice4_match_id_previously_was: () -> ::Integer?

    def choice4_match_id_before_last_save: () -> ::Integer?

    def choice4_match_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def choice4_match_id_in_database: () -> ::Integer?

    def saved_change_to_choice4_match_id: () -> ::Array[::Integer?]?

    def saved_change_to_choice4_match_id?: () -> bool

    def will_save_change_to_choice4_match_id?: () -> bool

    def restore_choice4_match_id!: () -> void

    def clear_choice4_match_id_change: () -> void

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void
  end
  include GeneratedAttributeMethods

  def player: () -> ::Player
  def player=: (::Player?) -> ::Player?
  def reload_player: () -> ::Player?
  def build_player: (untyped) -> ::Player
  def create_player: (untyped) -> ::Player
  def create_player!: (untyped) -> ::Player
  def choice1_match: () -> ::Match
  def choice1_match=: (::Match?) -> ::Match?
  def reload_choice1_match: () -> ::Match?
  def build_choice1_match: (untyped) -> ::Match
  def create_choice1_match: (untyped) -> ::Match
  def create_choice1_match!: (untyped) -> ::Match
  def choice2_match: () -> ::Match
  def choice2_match=: (::Match?) -> ::Match?
  def reload_choice2_match: () -> ::Match?
  def build_choice2_match: (untyped) -> ::Match
  def create_choice2_match: (untyped) -> ::Match
  def create_choice2_match!: (untyped) -> ::Match
  def choice3_match: () -> ::Match
  def choice3_match=: (::Match?) -> ::Match?
  def reload_choice3_match: () -> ::Match?
  def build_choice3_match: (untyped) -> ::Match
  def create_choice3_match: (untyped) -> ::Match
  def create_choice3_match!: (untyped) -> ::Match
  def choice4_match: () -> ::Match
  def choice4_match=: (::Match?) -> ::Match?
  def reload_choice4_match: () -> ::Match?
  def build_choice4_match: (untyped) -> ::Match
  def create_choice4_match: (untyped) -> ::Match
  def create_choice4_match!: (untyped) -> ::Match
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Round3CoursePreference::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::Round3CoursePreference, ::Integer]
    include ::Enumerable[::Round3CoursePreference]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Round3CoursePreference::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::Round3CoursePreference, ::Integer]
  end
end
