inherit_gem:
  rubocop-kyanagi:
    - ruby.yml
    - rails.yml
    - rspec.yml
    - factory_bot.yml

AllCops:
  SuggestExtensions: false

Layout/CommentIndentation:
  Enabled: true
  Exclude:
    - "config/**/*.rb"

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Rails/StrongParametersExpect:
  Enabled: false
