module MatchRule
  class Round3Hayabo2 < Base
    NUM_SEATS = 8
    NUM_BUTTONS = 8
    NUM_WINNERS = 4
    POINTS_TO_WIN = 18
    POINTS_ON_PUSHED_CORRECT = 3
    POINTS_ON_UNPUSHED_CORRECT = 2
    POINTS_ON_PUSHED_WRONG = -3
    POINTS_ON_UNPUSHED_WRONG = 0
    BONUS_POINTS_ON_SOLE_CORRECT = 1
    ADMIN_VIEW_TEMPLATE = "hayabo"

    include Hayabo
  end
end
