class ApplicationRecord < ::ActiveRecord::Base
end
class QuestionPlayerResult::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class YontakuPlayerPaper::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class Matching::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class Score::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class QuestionAllocation::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class Question::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ScoreOperation::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class Round < ::ActiveHash::Base
end
class ActiveRecord::Associations::CollectionProxy < ::ActiveRecord::Relation
end
class ActiveHash::Base < ::Object
end
class ActiveRecord::Relation < ::Object
end
module ActiveRecord::Associations
end
module ActiveHash
end
